// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.huiyuan2.cloud.basic.network.proto;

public final class Network {
  private Network() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnetwork.proto\022&com.huiyuan2.cloud.basi" +
      "c.network.proto\"\234\001\n\021NettyPacketHeader\022W\n" +
      "\007headers\030\001 \003(\0132F.com.huiyuan2.cloud.basi" +
      "c.network.proto.NettyPacketHeader.Header" +
      "sEntry\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001B*\n&com.huiyuan2.cloud.bas" +
      "ic.network.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_descriptor,
        new java.lang.String[] { "Headers", });
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_HeadersEntry_descriptor =
      internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_descriptor.getNestedTypes().get(0);
    internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huiyuan2_cloud_basic_network_proto_NettyPacketHeader_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
