// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registry.proto

package com.huiyuan2.cloud.basic.network.proto;

public final class Registry {
  private Registry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huiyuan2_cloud_basic_registry_proto_MetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huiyuan2_cloud_basic_registry_proto_MetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huiyuan2_cloud_basic_registry_proto_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huiyuan2_cloud_basic_registry_proto_SubscribeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016registry.proto\022\'com.huiyuan2.cloud.bas" +
      "ic.registry.proto\"Q\n\017MetadataRequest\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\023\n\013serviceType\030" +
      "\003 \001(\t\022\r\n\005event\030\004 \001(\005\"5\n\020SubscribeRequest" +
      "\022\023\n\013serviceType\030\001 \001(\t\022\014\n\004keys\030\002 \003(\tB*\n&c" +
      "om.huiyuan2.cloud.basic.network.protoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_huiyuan2_cloud_basic_registry_proto_MetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_huiyuan2_cloud_basic_registry_proto_MetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huiyuan2_cloud_basic_registry_proto_MetadataRequest_descriptor,
        new java.lang.String[] { "Key", "Value", "ServiceType", "Event", });
    internal_static_com_huiyuan2_cloud_basic_registry_proto_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_huiyuan2_cloud_basic_registry_proto_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huiyuan2_cloud_basic_registry_proto_SubscribeRequest_descriptor,
        new java.lang.String[] { "ServiceType", "Keys", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
