// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registry.proto

package com.huiyuan2.cloud.basic.network.proto;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huiyuan2.cloud.basic.registry.proto.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceType = 1;</code>
   * @return The serviceType.
   */
  java.lang.String getServiceType();
  /**
   * <code>string serviceType = 1;</code>
   * @return The bytes for serviceType.
   */
  com.google.protobuf.ByteString
      getServiceTypeBytes();

  /**
   * <code>repeated string keys = 2;</code>
   * @return A list containing the keys.
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 2;</code>
   * @return The count of keys.
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 2;</code>
   * @param index The index of the element to return.
   * @return The keys at the given index.
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keys at the given index.
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
